name: Playground for GitHub App Installation Token
on:
  workflow_dispatch:

env:
  repo-name: tanimon/dummy-private-repo

jobs:
  checkout-another-repo-without-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.repo-name }}
      - run: cat README.md

  checkout-another-repo-with-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.repo-name }}
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - run: cat README.md
