name: Hello
on:
  workflow_dispatch:

inputs:
  name:
    description: 'Name to greet'
    required: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello, ${{ inputs.name }}!"
