on:
  workflow_call:
    inputs:
      awsRoleArn:
        type: string
        required: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm

      - run: npm i -g npm@9.4.1

      - run: npm ci

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.awsRoleArn }}
          aws-region: ap-northeast-1

      - run: aws sts get-caller-identity

      - run: npm run bootstrap -w iac

      - run: npm run deploy -w iac
